project:
  type: website
  render:
    - "*.qmd"
    - "!garage/"
    - "!tmp*qmd"
    - "!risorse/"
  output-dir: docs
  resources:
  - "googlecd08604f4edafe6e.html"

website:
  site-url: https://aborruso.github.io
  title: "aborruso's website"
  favicon: "risorse/favicon.png"
  page-navigation: true
  twitter-card:
    creator: "@aborruso"
    card-style: summary_large_image
    image: "/risorse/twitter-card.png"
  open-graph:
    locale: it_IT
    image: "/risorse/opengraph.png"
  repo-url: https://github.com/aborruso/aborruso.github.io
  repo-actions: [edit, issue]
  navbar:
    background: "#75aadb"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: til.qmd
        text: TIL
  page-footer:
    left: "Costruito con [quarto](https://quarto.org) 😍 | Contenuti in [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.it)"
    right:
      - icon: twitter
        href: https://twitter.com/aborruso
      - icon: rss
        href: blog.xml
      - icon: github
        href: https://github.com/aborruso/aborruso.github.io

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: it
    dir: ltr
    link-external-newwindow: true
    link-external-filter: '.*aborruso\.github\.io\.*'
    include-in-header: include/rss.html

execute:
  daemon: false
  freeze: auto


language:
  title-block-author-single: "Autore/Autrice"
  listing-page-field-author: "Autore/Autrice"
