project:
  type: website
  output-dir: docs

website:
  site-url: https://aborruso.github.io/
  title: "aborruso's website"
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: til.qmd
        text: TIL
  page-footer:
    left: "Contenuti in [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.it) | Costruito con [quarto](https://quarto.org)"
    right:
      - icon: twitter
        href: https://twitter.com/aborruso
      - icon: rss
        href: blog.xml
      - icon: github
        href: https://github.com/aborruso/aborruso.github.io

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: ita
    dir: ltr


