---
title: "Il meraviglioso fzf"
description: "E gli shortcut che dimentico sempre"
date: "2024-09-05"
draft: false
categories:
  - search
  - til
  - cli
---


> [fzf](https://github.com/junegunn/fzf) is an interactive filter program for any kind of list; files, command history, processes, hostnames, bookmarks, git commits, etc. It implements a "fuzzy" matching algorithm, so you can quickly type in patterns with omitted characters and still get the results you want.

- `CTRL+R` per cercare nella *history* dei comandi;
- `ALT+C` per avere la lista delle cartelle nella cartella corrente;
- `CTRL+T` per avere la lista dei file della cartella corrente;
- `ALT+P` per avere, da dentro `fzf`, la preview del file selezionato;
- `zi` in accoppiata con [`zoxide`](https://github.com/ajeetdsouza/zoxide) per navigare velocemente tra le cartelle più "usate".

A proposito della *preview*, è comoda questa configurazione, in cui si usa [`bat`](https://github.com/sharkdp/bat) per la preview:

```bash
export FZF_DEFAULT_OPTS="--bind 'alt-p:toggle-preview' --preview-window=hidden --preview 'batcat --style=numbers --color=always --line-range :500 {}'"
```

Inoltre, quando si scrive un comando si può attivare un auto completamento globale inserendo `**` e poi `TAB`. Qualche esempio:

- `ls **` e poi `TAB` per avere la lista di tutti i file e cartelle;
- `cat **` e poi `TAB` per avere la lista di tutti i file.

Se vuoi vedere fzf in azione:

{{< video https://www.youtube.com/watch?v=qgG5Jhi_Els >}}
