on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - '.github/copilot-instructions.md'

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # - name: setup r
      #   uses: r-lib/actions/setup-r@v2

      - name: Setup locale it_IT.UTF-8
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen it_IT.UTF-8
          sudo update-locale LANG=it_IT.UTF-8

      - name: installa moduli python
        run: |-
          pip3 install nbformat
          pip3 install jupyter
          pip3 install pandas
          pip3 install altair

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.549

      # - name: Install rmarkdown
      #   run: Rscript -e 'install.packages("rmarkdown")'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
